name: Build and Version

on:
  push:
    tags:
      - 'v*.*.*' # e.g., v1.0.0

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Get version from tag
        run: echo "VERSION=${GITHUB_REF_NAME}" >> $GITHUB_ENV

      - name: Update README version
        run: |
          if grep -q "Version:" README.md; then
            sed -i "s/Version: .*/Version: ${VERSION}/" README.md
          else
            echo -e "\n## Version\nVersion: ${VERSION}" >> README.md
          fi

      - name: Commit README update
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Update README for ${VERSION}" || echo "No changes to commit"
          git push

      - name: Create build directory
        run: |
          mkdir build
          cp -r *.html build/
          cp -r assets build/ || true

      - name: Zip build files
        run: zip -r workdays-${VERSION}.zip build/

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: workdays-build
          path: workdays-${VERSION}.zip
          
