name: Lint HTML/CSS/JS

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install linters
        run: |
          npm install -g htmlhint stylelint eslint

      - name: Lint HTML
        run: htmlhint "**/*.html"

      - name: Lint CSS
        run: stylelint "**/*.css" || true

      - name: Lint JS
        run: eslint "**/*.js" || true
